# Generated by Django 5.2.4 on 2025-07-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fone',
            new_name='phone',
        ),
    ]
