# Generated by Django 5.2.4 on 2025-07-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_rename_fone_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('gerente', 'Gerente'), ('secretaria', 'Secretaria'), ('operador', 'Operador'), ('encarregado', 'Encarregado')], max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
