# Generated by Django 5.2.4 on 2025-07-28 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quote', '0002_alter_quote_total_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], max_length=20)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='quote.quote')),
            ],
        ),
    ]
